// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.12.4
// source: common.proto

package service

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Model struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamp.Timestamp   `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamp.Timestamp   `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *Model) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Model) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Model) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Model) GetDeletedAt() *timestamp.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type Review struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         *Model                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	ProductId     uint32                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Rating        int32                  `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
	LikesCount    int32                  `protobuf:"varint,5,opt,name=likes_count,json=likesCount,proto3" json:"likes_count,omitempty"`
	Comment       string                 `protobuf:"bytes,6,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Review) Reset() {
	*x = Review{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Review) ProtoMessage() {}

func (x *Review) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Review.ProtoReflect.Descriptor instead.
func (*Review) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *Review) GetModel() *Model {
	if x != nil {
		return x.Model
	}
	return nil
}

func (x *Review) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *Review) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Review) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Review) GetLikesCount() int32 {
	if x != nil {
		return x.LikesCount
	}
	return 0
}

func (x *Review) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type Question struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Model     *Model                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	ProductId uint32                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	// Types that are valid to be assigned to Author:
	//
	//	*Question_UserId
	//	*Question_GuestId
	Author        isQuestion_Author `protobuf_oneof:"author"`
	QuestionText  string            `protobuf:"bytes,5,opt,name=question_text,json=questionText,proto3" json:"question_text,omitempty"`
	AnswerText    string            `protobuf:"bytes,6,opt,name=answer_text,json=answerText,proto3" json:"answer_text,omitempty"`
	LikesCount    int32             `protobuf:"varint,7,opt,name=likes_count,json=likesCount,proto3" json:"likes_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *Question) GetModel() *Model {
	if x != nil {
		return x.Model
	}
	return nil
}

func (x *Question) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *Question) GetAuthor() isQuestion_Author {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *Question) GetUserId() uint32 {
	if x != nil {
		if x, ok := x.Author.(*Question_UserId); ok {
			return x.UserId
		}
	}
	return 0
}

func (x *Question) GetGuestId() []byte {
	if x != nil {
		if x, ok := x.Author.(*Question_GuestId); ok {
			return x.GuestId
		}
	}
	return nil
}

func (x *Question) GetQuestionText() string {
	if x != nil {
		return x.QuestionText
	}
	return ""
}

func (x *Question) GetAnswerText() string {
	if x != nil {
		return x.AnswerText
	}
	return ""
}

func (x *Question) GetLikesCount() int32 {
	if x != nil {
		return x.LikesCount
	}
	return 0
}

type isQuestion_Author interface {
	isQuestion_Author()
}

type Question_UserId struct {
	UserId uint32 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3,oneof"`
}

type Question_GuestId struct {
	GuestId []byte `protobuf:"bytes,4,opt,name=guest_id,json=guestId,proto3,oneof"`
}

func (*Question_UserId) isQuestion_Author() {}

func (*Question_GuestId) isQuestion_Author() {}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc8\x01\n" +
	"\x05Model\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"\xb7\x01\n" +
	"\x06Review\x12\"\n" +
	"\x05model\x18\x01 \x01(\v2\f.proto.ModelR\x05model\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\rR\tproductId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\rR\x06userId\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\x05R\x06rating\x12\x1f\n" +
	"\vlikes_count\x18\x05 \x01(\x05R\n" +
	"likesCount\x12\x18\n" +
	"\acomment\x18\x06 \x01(\tR\acomment\"\xf6\x01\n" +
	"\bQuestion\x12\"\n" +
	"\x05model\x18\x01 \x01(\v2\f.proto.ModelR\x05model\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\rR\tproductId\x12\x19\n" +
	"\auser_id\x18\x03 \x01(\rH\x00R\x06userId\x12\x1b\n" +
	"\bguest_id\x18\x04 \x01(\fH\x00R\aguestId\x12#\n" +
	"\rquestion_text\x18\x05 \x01(\tR\fquestionText\x12\x1f\n" +
	"\vanswer_text\x18\x06 \x01(\tR\n" +
	"answerText\x12\x1f\n" +
	"\vlikes_count\x18\a \x01(\x05R\n" +
	"likesCountB\b\n" +
	"\x06authorB\x0fZ\r./pkg/serviceb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_common_proto_goTypes = []any{
	(*Model)(nil),               // 0: proto.Model
	(*Review)(nil),              // 1: proto.Review
	(*Question)(nil),            // 2: proto.Question
	(*timestamp.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_common_proto_depIdxs = []int32{
	3, // 0: proto.Model.created_at:type_name -> google.protobuf.Timestamp
	3, // 1: proto.Model.updated_at:type_name -> google.protobuf.Timestamp
	3, // 2: proto.Model.deleted_at:type_name -> google.protobuf.Timestamp
	0, // 3: proto.Review.model:type_name -> proto.Model
	0, // 4: proto.Question.model:type_name -> proto.Model
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	file_common_proto_msgTypes[2].OneofWrappers = []any{
		(*Question_UserId)(nil),
		(*Question_GuestId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
