// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.12.4
// source: questions.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetQuestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint32                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuestionsRequest) Reset() {
	*x = GetQuestionsRequest{}
	mi := &file_questions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionsRequest) ProtoMessage() {}

func (x *GetQuestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_questions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionsRequest.ProtoReflect.Descriptor instead.
func (*GetQuestionsRequest) Descriptor() ([]byte, []int) {
	return file_questions_proto_rawDescGZIP(), []int{0}
}

func (x *GetQuestionsRequest) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *GetQuestionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetQuestionsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type QuestionListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Questions     []*Question            `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionListResponse) Reset() {
	*x = QuestionListResponse{}
	mi := &file_questions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionListResponse) ProtoMessage() {}

func (x *QuestionListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_questions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionListResponse.ProtoReflect.Descriptor instead.
func (*QuestionListResponse) Descriptor() ([]byte, []int) {
	return file_questions_proto_rawDescGZIP(), []int{1}
}

func (x *QuestionListResponse) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

var File_questions_proto protoreflect.FileDescriptor

const file_questions_proto_rawDesc = "" +
	"\n" +
	"\x0fquestions.proto\x12\x05proto\x1a\fcommon.proto\"b\n" +
	"\x13GetQuestionsRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\rR\tproductId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"E\n" +
	"\x14QuestionListResponse\x12-\n" +
	"\tquestions\x18\x01 \x03(\v2\x0f.proto.QuestionR\tquestions2d\n" +
	"\x0fQuestionService\x12Q\n" +
	"\x16GetQuestionsForProduct\x12\x1a.proto.GetQuestionsRequest\x1a\x1b.proto.QuestionListResponseB\x0fZ\r./pkg/serviceb\x06proto3"

var (
	file_questions_proto_rawDescOnce sync.Once
	file_questions_proto_rawDescData []byte
)

func file_questions_proto_rawDescGZIP() []byte {
	file_questions_proto_rawDescOnce.Do(func() {
		file_questions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_questions_proto_rawDesc), len(file_questions_proto_rawDesc)))
	})
	return file_questions_proto_rawDescData
}

var file_questions_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_questions_proto_goTypes = []any{
	(*GetQuestionsRequest)(nil),  // 0: proto.GetQuestionsRequest
	(*QuestionListResponse)(nil), // 1: proto.QuestionListResponse
	(*Question)(nil),             // 2: proto.Question
}
var file_questions_proto_depIdxs = []int32{
	2, // 0: proto.QuestionListResponse.questions:type_name -> proto.Question
	0, // 1: proto.QuestionService.GetQuestionsForProduct:input_type -> proto.GetQuestionsRequest
	1, // 2: proto.QuestionService.GetQuestionsForProduct:output_type -> proto.QuestionListResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_questions_proto_init() }
func file_questions_proto_init() {
	if File_questions_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_questions_proto_rawDesc), len(file_questions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_questions_proto_goTypes,
		DependencyIndexes: file_questions_proto_depIdxs,
		MessageInfos:      file_questions_proto_msgTypes,
	}.Build()
	File_questions_proto = out.File
	file_questions_proto_goTypes = nil
	file_questions_proto_depIdxs = nil
}
