// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.12.4
// source: reviews.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetReviewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint32                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReviewsRequest) Reset() {
	*x = GetReviewsRequest{}
	mi := &file_reviews_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReviewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReviewsRequest) ProtoMessage() {}

func (x *GetReviewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reviews_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReviewsRequest.ProtoReflect.Descriptor instead.
func (*GetReviewsRequest) Descriptor() ([]byte, []int) {
	return file_reviews_proto_rawDescGZIP(), []int{0}
}

func (x *GetReviewsRequest) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *GetReviewsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetReviewsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ReviewListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reviews       []*Review              `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewListResponse) Reset() {
	*x = ReviewListResponse{}
	mi := &file_reviews_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewListResponse) ProtoMessage() {}

func (x *ReviewListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reviews_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewListResponse.ProtoReflect.Descriptor instead.
func (*ReviewListResponse) Descriptor() ([]byte, []int) {
	return file_reviews_proto_rawDescGZIP(), []int{1}
}

func (x *ReviewListResponse) GetReviews() []*Review {
	if x != nil {
		return x.Reviews
	}
	return nil
}

var File_reviews_proto protoreflect.FileDescriptor

const file_reviews_proto_rawDesc = "" +
	"\n" +
	"\rreviews.proto\x12\x05proto\x1a\fcommon.proto\"`\n" +
	"\x11GetReviewsRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\rR\tproductId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"=\n" +
	"\x12ReviewListResponse\x12'\n" +
	"\areviews\x18\x01 \x03(\v2\r.proto.ReviewR\areviews2\\\n" +
	"\rReviewService\x12K\n" +
	"\x14GetReviewsForProduct\x12\x18.proto.GetReviewsRequest\x1a\x19.proto.ReviewListResponseB\x0fZ\r./pkg/serviceb\x06proto3"

var (
	file_reviews_proto_rawDescOnce sync.Once
	file_reviews_proto_rawDescData []byte
)

func file_reviews_proto_rawDescGZIP() []byte {
	file_reviews_proto_rawDescOnce.Do(func() {
		file_reviews_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reviews_proto_rawDesc), len(file_reviews_proto_rawDesc)))
	})
	return file_reviews_proto_rawDescData
}

var file_reviews_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_reviews_proto_goTypes = []any{
	(*GetReviewsRequest)(nil),  // 0: proto.GetReviewsRequest
	(*ReviewListResponse)(nil), // 1: proto.ReviewListResponse
	(*Review)(nil),             // 2: proto.Review
}
var file_reviews_proto_depIdxs = []int32{
	2, // 0: proto.ReviewListResponse.reviews:type_name -> proto.Review
	0, // 1: proto.ReviewService.GetReviewsForProduct:input_type -> proto.GetReviewsRequest
	1, // 2: proto.ReviewService.GetReviewsForProduct:output_type -> proto.ReviewListResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_reviews_proto_init() }
func file_reviews_proto_init() {
	if File_reviews_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reviews_proto_rawDesc), len(file_reviews_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reviews_proto_goTypes,
		DependencyIndexes: file_reviews_proto_depIdxs,
		MessageInfos:      file_reviews_proto_msgTypes,
	}.Build()
	File_reviews_proto = out.File
	file_reviews_proto_goTypes = nil
	file_reviews_proto_depIdxs = nil
}
